name: 🐛 Bug Report
about: Found a bug? Help us squash it.
labels: ["bug"]

body:

- type: markdown
  attributes:
    value: |
      While we'd love to be able to support every person on their projects, that would simply be infeasible. Luckily, that's what the helpful developer community over at Stack Overflow is for! Please [create a question there](https://stackoverflow.com/questions/ask?tags=python) if what you're looking for is a programming question or you need help with an integration.

      Also, consider [supporting the project](https://github.com/sponsors/alexdlaird) to have your request prioritized.

- type: input
  id: os-version
  attributes:
    label: Operating System
    placeholder: macOS 10.14.5
  validations:
    required: true

- type: input
  id: python-version
  attributes:
    label: Python Version
    placeholder: 3.9.2
  validations:
    required: true

- type: input
  id: library-version
  attributes:
    label: "`amazon-orders` Version"
    placeholder: 1.0.3
  validations:
    required: true

- type: textarea
  id: describe-the-bug
  attributes:
    label: Describe the Bug
    description: A clear and concise description of what the bug is, including exceptions thrown.
  validations:
    required: true

- type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to Reproduce
    description: A snippet of the code used to reproduce the behavior.
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: A brief description of what you expected to happen.
  validations:
    required: true
